version: 2.1
orbs:
  orb-tools: circleci/orb-tools@12.0
  unity: {}

filters: &filters
  tags:
    only: /.*/

release-filters: &release-filters
  branches:
    ignore: /.*/
  tags:
    only: /^v[0-9]+\.[0-9]+\.[0-9]+$/

pre-steps:
  mono: &mono
    - run:
        name: "Clone the demo project"
        command: |
          # Clone the "mono" demo project
          git clone --branch master --single-branch https://github.com/EricRibeiro/Unity2D-Demo-Game-CI-CD.git ../Unity2D-Demo-Game-CI-CD

          # Clone the Unity orb
          git clone https://github.com/game-ci/unity-orb.git .

          # Move the demo project to the project folder
          mv ../Unity2D-Demo-Game-CI-CD ./Unity2D-Demo-Game-CI-CD
  il2cpp: &il2cpp
    - run:
        name: "Clone the demo project"
        command: |
          # Clone the "il2cpp" demo project
          git clone --branch windows-il2cpp --single-branch https://github.com/EricRibeiro/Unity2D-Demo-Game-CI-CD.git ../Unity2D-Demo-Game-CI-CD

          # Clone the Unity orb
          git clone https://github.com/game-ci/unity-orb.git .

          # Move the demo project to the project folder
          mv ../Unity2D-Demo-Game-CI-CD ./Unity2D-Demo-Game-CI-CD
  custom-build-method: &custom-build-method
    - run:
        name: "Clone the demo project"
        command: |
          # Clone the demo project with custom build method
          git clone --branch custom-build-method --single-branch https://github.com/EricRibeiro/Unity2D-Demo-Game-CI-CD.git ../Unity2D-Demo-Game-CI-CD

          # Clone the Unity orb
          git clone https://github.com/game-ci/unity-orb.git .

          # Move the demo project to the project folder
          mv ../Unity2D-Demo-Game-CI-CD ./Unity2D-Demo-Game-CI-CD

jobs:
  test-persist-to-workspace:
    docker:
      - image: cimg/base:2023.06
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Check attached file exists
          command: ls Builds/StandaloneLinux64/UnityPlayer.so

  test-compress-persist-to-workspace:
    docker:
      - image: cimg/base:2023.06
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Check attached file exists
          command: ls StandaloneLinux64.tar.gz

workflows:
  test-build:
    jobs:
       - orb-tools/pack:
          filters: *release-filters
       - orb-tools/publish:
          orb_name: game-ci/unity
          vcs_type: << pipeline.project.type >>
          pub_type: production
          requires:
            - orb-tools/pack
# TODO: Revert the commit that commented these lines (other jobs will appear again too)
#            - test-linux
#            - test-linux-with-custom-parameters
#            # - test-windows # TODO: Investigate Windows activation error
#            # - test-windows-with-custom-parameters # TODO: Investigate Windows activation error
#            - test-osx
#            - test-osx-with-custom-parameters
#            - build-linux64-il2cpp
#            # - build-Windows64-il2cpp # TODO: Investigate Windows activation error
#            - build-osx-il2cpp
#            - build-linux64-mono
#            - build-Windows64-mono
#            - build-osx-mono
#            - build-webgl
#            - build-android
#            - build-ios
#            # - build-tvOS # TODO: Investigate Windows activation error
#            - build-without-artifacts
#            # - build-with-custom-method-windows # TODO: Investigate Windows activation error
#            - build-with-custom-method-osx
#            - build-with-custom-method-linux
          context: orb-publishing
          filters: *release-filters
