version: 2.1
orbs:
  unity: game-ci/unity@dev:<<pipeline.git.revision>>
  orb-tools: circleci/orb-tools@11.1

filters: &filters
  tags:
    only: /.*/

pre-steps:
  mono: &mono
    - run:
        name: "Clone the demo project"
        command: |
          # Clone the "mono" demo project
          git clone --branch master --single-branch https://github.com/EricRibeiro/Unity2D-Demo-Game-CI-CD.git ../Unity2D-Demo-Game-CI-CD
          
          # Clone the Unity orb
          git clone https://github.com/game-ci/unity-orb.git .

          # Move the demo project to the project folder
          mv ../Unity2D-Demo-Game-CI-CD ./Unity2D-Demo-Game-CI-CD    
  il2cpp: &il2cpp
    - run:
        name: "Clone the demo project"
        command: |
          # Clone the "il2cpp" demo project
          git clone --branch windows-il2cpp --single-branch https://github.com/EricRibeiro/Unity2D-Demo-Game-CI-CD.git ../Unity2D-Demo-Game-CI-CD

          # Clone the Unity orb
          git clone https://github.com/game-ci/unity-orb.git .

          # Move the demo project to the project folder
          mv ../Unity2D-Demo-Game-CI-CD ./Unity2D-Demo-Game-CI-CD    
  custom-build-method: &custom-build-method
    - run:
        name: "Clone the demo project"
        command: |
          # Clone the demo project with custom build method
          git clone --branch custom-build-method --single-branch https://github.com/EricRibeiro/Unity2D-Demo-Game-CI-CD.git ../Unity2D-Demo-Game-CI-CD

          # Clone the Unity orb
          git clone https://github.com/game-ci/unity-orb.git .

          # Move the demo project to the project folder
          mv ../Unity2D-Demo-Game-CI-CD ./Unity2D-Demo-Game-CI-CD

workflows:
  test-build:
    jobs:
      # Other Tests
      - unity/build:
          name: "build-with-custom-method-windows"
          step-name: "Build with custom method in Windows"
          unity-license-var-name: "UNITY_ENCODED_LICENSE_2021"
          unity-username-var-name: "UNITY_USERNAME"
          unity-password-var-name: "UNITY_PASSWORD"
          executor:
            name: "unity/windows-runner"
            resource_class: "ericribeiro/unity-ec2"
            editor_version: "2021.3.2f1"
            target_platform: "windows-il2cpp"
          project-path: "Unity2D-Demo-Game-CI-CD/src"
          build-target: StandaloneWindows64
          build-method: "MyCustomBuildCommand.MyCustomBuildMethod"
          custom-parameters: "-customParam1 potato -customParam2 tomato -customParam3 $CIRCLE_WORKFLOW_ID -DetailedBuildReport"
          filters: *filters
          context: orb-testing-unity
          pre-steps: *custom-build-method

      - orb-tools/pack:
          filters: *filters
      - orb-tools/publish:
          orb-name: game-ci/unity
          vcs-type: << pipeline.project.type >>
          pub-type: production
          requires:
            - orb-tools/pack
            - build-with-custom-method-windows
          context: orb-publishing
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+$/