version: 2.1
orbs:
  unity: ericribeiro/unity@dev:<<pipeline.git.revision>>
  orb-tools: circleci/orb-tools@11.1

filters: &filters
  tags:
    only: /.*/

workflows:
  test-deploy:
    jobs:
      # It's not possible to test this now because the orb repository itself doesn't have a test project
      # And I am having a hard time cloning the repository because of CCI checkout step inner workings
      # - unity/test:
      #     step-name: "Check if tests run and the results are stored"
      #     unity-license-var-name: "ACTIVATION_ULF_ENC"
      #     tag: "ubuntu-2018.4.13f1-base-0.7"
      #     project-path: "Unity2D-Demo-Game-CI-CD/src"
      #     test-platform: "playmode"
      #     filters: *filters
      #     context: orb-unity-testing
      # - unity/build:
      #     step-name: "Check if the project is built and artifacts are uploaded"
      #     unity-license-var-name: "ACTIVATION_ULF_ENC"
      #     tag: "ubuntu-2018.4.13f1-base-0.7"
      #     project-path: "Unity2D-Demo-Game-CI-CD/src"
      #     build-target: StandaloneLinux64
      #     requires:
      #       - unity/test
      #     filters: *filters
      #     context: orb-unity-testing
      - orb-tools/pack:
          filters: *filters
      - orb-tools/publish:
          orb-name: ericribeiro/unity
          vcs-type: << pipeline.project.type >>
          pub-type: production
          requires:
            - orb-tools/pack
            # - unity/test
            # - unity/build
          context: orb-publishing
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+$/