version: 2.1
orbs:
  unity: game-ci/unity@dev:<<pipeline.git.revision>>
  orb-tools: circleci/orb-tools@11.1

filters: &filters
  tags:
    only: /.*/

jobs:
  build-il2cpp:
    description: >
      Simple drop-in job to build your Unity game.

    parameters:
      step-name:
        type: string
        default: Build the project
        description: |
          Specify a custom step name for the build command, if desired.
      executor:
        type: executor
        description: |
          Pick an Executor to run the build job with.
      unity-username-var-name:
        type: env_var_name
        default: "UNITY_USERNAME"
        description: |
          Enter the name of the environment variable containing your Unity username.
          This is only necessary if you have a Plus or Pro license.
      unity-password-var-name:
        type: env_var_name
        default: "UNITY_PASSWORD"
        description: |
          Enter the name of the environment variable containing your Unity password.
          This is only necessary if you have a Plus or Pro license.
      unity-serial-var-name:
        type: env_var_name
        default: "UNITY_SERIAL"
        description: |
          Enter the name of the environment variable containing your Unity serial number.
          This is only necessary if you have a Plus or Pro license.
      unity-license-var-name:
        type: env_var_name
        default: "UNITY_ENCODED_LICENSE"
        description: |
          Enter the name of the environment variable containing your Unity license file encoded in base64.
          A different license must be provided for every Unity major version.
          This is only necessary if you have a Personal license.
      project-path:
        type: string
        default: "."
        description: |
          Enter the path of your Unity project.
          This should be the directory that has an "Assets" folder inside it.
      build-target:
        type: string
        description: |
          The target platform of your build.
          Accepted arguments vary with Unity's version and can be found in the docs: https://docs.unity3d.com/2022.2/Documentation/ScriptReference/BuildTarget.html
      build-name:
        type: string
        default: "UnityBuild"
        description: |
          Enter the name for this build.
      compress:
        type: boolean
        default: true
        description: |
          Whether to compress the build output to a ".tar.gz" archive.
          This is recommended if you want to download the build artifacts from the GameCI dashboard.
          If left to "false" for decompressed WebGL builds, the built project can be run directly from the GameCI dashboard.

    executor: << parameters.executor >> 

    steps:
      - run:
          name: "Clone CircleCI demo repository"
          command: |
            git clone https://github.com/EricRibeiro/Unity2D-Demo-Game-CI-CD.git
            cd Unity2D-Demo-Game-CI-CD
            git fetch --all
            git checkout windows-il2cpp
      - unity/prepare-env:
          unity-username-var-name: << parameters.unity-username-var-name >>
          unity-password-var-name: << parameters.unity-password-var-name >>
          unity-serial-var-name: << parameters.unity-serial-var-name >>
          unity-license-var-name: << parameters.unity-license-var-name >>
          project-path: <<parameters.project-path>>
          cache-version: v2
      - unity/build:
          step-name: << parameters.step-name >>
          build-name: <<parameters.build-name>>
          build-target: <<parameters.build-target>>
          project-path: <<parameters.project-path>>
          compress: <<parameters.compress>>
          cache-version: v2
      - unity/return-license:
          unity-username-var-name: << parameters.unity-username-var-name >>
          unity-password-var-name: << parameters.unity-password-var-name >>
  
  build-mono:
    description: >
      Simple drop-in job to build your Unity game.

    parameters:
      step-name:
        type: string
        default: Build the project
        description: |
          Specify a custom step name for the build command, if desired.
      executor:
        type: executor
        description: |
          Pick an Executor to run the build job with.
      unity-username-var-name:
        type: env_var_name
        default: "UNITY_USERNAME"
        description: |
          Enter the name of the environment variable containing your Unity username.
          This is only necessary if you have a Plus or Pro license.
      unity-password-var-name:
        type: env_var_name
        default: "UNITY_PASSWORD"
        description: |
          Enter the name of the environment variable containing your Unity password.
          This is only necessary if you have a Plus or Pro license.
      unity-serial-var-name:
        type: env_var_name
        default: "UNITY_SERIAL"
        description: |
          Enter the name of the environment variable containing your Unity serial number.
          This is only necessary if you have a Plus or Pro license.
      unity-license-var-name:
        type: env_var_name
        default: "UNITY_ENCODED_LICENSE"
        description: |
          Enter the name of the environment variable containing your Unity license file encoded in base64.
          A different license must be provided for every Unity major version.
          This is only necessary if you have a Personal license.
      project-path:
        type: string
        default: "."
        description: |
          Enter the path of your Unity project.
          This should be the directory that has an "Assets" folder inside it.
      build-target:
        type: string
        description: |
          The target platform of your build.
          Accepted arguments vary with Unity's version and can be found in the docs: https://docs.unity3d.com/2022.2/Documentation/ScriptReference/BuildTarget.html
      build-name:
        type: string
        default: "UnityBuild"
        description: |
          Enter the name for this build.
      compress:
        type: boolean
        default: true
        description: |
          Whether to compress the build output to a ".tar.gz" archive.
          This is recommended if you want to download the build artifacts from the GameCI dashboard.
          If left to "false" for decompressed WebGL builds, the built project can be run directly from the GameCI dashboard.

    executor: << parameters.executor >> 

    steps:
      - run:
          name: "Clone CircleCI demo repository"
          command: |
            git clone https://github.com/EricRibeiro/Unity2D-Demo-Game-CI-CD.git
      - unity/prepare-env:
          unity-username-var-name: << parameters.unity-username-var-name >>
          unity-password-var-name: << parameters.unity-password-var-name >>
          unity-serial-var-name: << parameters.unity-serial-var-name >>
          unity-license-var-name: << parameters.unity-license-var-name >>
          project-path: <<parameters.project-path>>
      - unity/build:
          step-name: << parameters.step-name >>
          build-name: <<parameters.build-name>>
          build-target: <<parameters.build-target>>
          project-path: <<parameters.project-path>>
          compress: <<parameters.compress>>
      - unity/return-license:
          unity-username-var-name: << parameters.unity-username-var-name >>
          unity-password-var-name: << parameters.unity-password-var-name >>

  build:
    description: >
      Simple drop-in job to build your Unity game.

    parameters:
      step-name:
        type: string
        default: Build the project
        description: |
          Specify a custom step name for the build command, if desired.
      executor:
        type: executor
        description: |
          Pick an Executor to run the build job with.
      unity-username-var-name:
        type: env_var_name
        default: "UNITY_USERNAME"
        description: |
          Enter the name of the environment variable containing your Unity username.
          This is only necessary if you have a Plus or Pro license.
      unity-password-var-name:
        type: env_var_name
        default: "UNITY_PASSWORD"
        description: |
          Enter the name of the environment variable containing your Unity password.
          This is only necessary if you have a Plus or Pro license.
      unity-serial-var-name:
        type: env_var_name
        default: "UNITY_SERIAL"
        description: |
          Enter the name of the environment variable containing your Unity serial number.
          This is only necessary if you have a Plus or Pro license.
      unity-license-var-name:
        type: env_var_name
        default: "UNITY_ENCODED_LICENSE"
        description: |
          Enter the name of the environment variable containing your Unity license file encoded in base64.
          A different license must be provided for every Unity major version.
          This is only necessary if you have a Personal license.
      project-path:
        type: string
        default: "."
        description: |
          Enter the path of your Unity project.
          This should be the directory that has an "Assets" folder inside it.
      build-target:
        type: string
        description: |
          The target platform of your build.
          Accepted arguments vary with Unity's version and can be found in the docs: https://docs.unity3d.com/2022.2/Documentation/ScriptReference/BuildTarget.html
      build-name:
        type: string
        default: "UnityBuild"
        description: |
          Enter the name for this build.
      compress:
        type: boolean
        default: true
        description: |
          Whether to compress the build output to a ".tar.gz" archive.
          This is recommended if you want to download the build artifacts from the GameCI dashboard.
          If left to "false" for decompressed WebGL builds, the built project can be run directly from the GameCI dashboard.

    executor: << parameters.executor >> 

    steps:
      - run:
          name: "Clone CircleCI demo repository"
          command: |
            git clone https://github.com/EricRibeiro/Unity2D-Demo-Game-CI-CD.git
      - unity/prepare-env:
          unity-username-var-name: << parameters.unity-username-var-name >>
          unity-password-var-name: << parameters.unity-password-var-name >>
          unity-serial-var-name: << parameters.unity-serial-var-name >>
          unity-license-var-name: << parameters.unity-license-var-name >>
          project-path: <<parameters.project-path>>
      - unity/build:
          step-name: << parameters.step-name >>
          build-name: <<parameters.build-name>>
          build-target: <<parameters.build-target>>
          project-path: <<parameters.project-path>>
          compress: <<parameters.compress>>
      - unity/return-license:
          unity-username-var-name: << parameters.unity-username-var-name >>
          unity-password-var-name: << parameters.unity-password-var-name >>

  test:
    description: >
      Simple drop-in job to build your Unity game.

    parameters:
      step-name:
        type: string
        default: Run tests
        description: |
          Specify a custom step name for the test command, if desired.
      executor:
        type: executor
        description: |
          Pick an Executor to run the build job with.
      unity-username-var-name:
        type: env_var_name
        default: "UNITY_USERNAME"
        description: |
          Enter the name of the environment variable containing your Unity username.
          This is only necessary if you have a Plus or Pro license.
      unity-password-var-name:
        type: env_var_name
        default: "UNITY_PASSWORD"
        description: |
          Enter the name of the environment variable containing your Unity password.
          This is only necessary if you have a Plus or Pro license.
      unity-serial-var-name:
        type: env_var_name
        default: "UNITY_SERIAL"
        description: |
          Enter the name of the environment variable containing your Unity serial number.
          This is only necessary if you have a Plus or Pro license.
      unity-license-var-name:
        type: env_var_name
        default: "UNITY_ENCODED_LICENSE"
        description: |
          Enter the name of the environment variable containing your Unity license file encoded in base64.
          A different license must be provided for every Unity major version.
          This is only necessary if you have a Personal license.
      project-path:
        type: string
        default: "."
        description: |
          Enter the path of your Unity project.
          This should be the directory that has an "Assets" folder inside it.
      test-platform:
        type: string
        default: "editmode"
        description: |
          Specify the test platform to run tests on.
          Valid values are "editmode", "playmode" and Unity's target builds.
          More information can be found on: https://docs.unity3d.com/Packages/com.unity.test-framework@2.0/manual/reference-command-line.html

    executor: << parameters.executor >>

    steps:
      - run:
          name: "Clone CircleCI demo repository"
          command: |
            git clone https://github.com/EricRibeiro/Unity2D-Demo-Game-CI-CD.git
      - unity/prepare-env:
          unity-username-var-name: << parameters.unity-username-var-name >>
          unity-password-var-name: << parameters.unity-password-var-name >>
          unity-serial-var-name: << parameters.unity-serial-var-name >>
          unity-license-var-name: << parameters.unity-license-var-name >>
          project-path: <<parameters.project-path>>
      - unity/test:
          step-name: << parameters.step-name >>
          test-platform: << parameters.test-platform >>
          project-path: << parameters.project-path >>
      - unity/return-license:
          unity-username-var-name: << parameters.unity-username-var-name >>
          unity-password-var-name: << parameters.unity-password-var-name >>

workflows:
  test-build:
    jobs:
      # Tests
      - test:
          name: "test-linux-serial"
          step-name: "Check if the tests run and results are uploaded"
          unity-username-var-name: "UNITY_USERNAME"
          unity-password-var-name: "UNITY_PASSWORD"
          unity-serial-var-name: "UNITY_SERIAL_2021"
          executor:
            name: "unity/ubuntu"
            target_platform: "linux-il2cpp"
            editor_version: "2021.3.1f1"
            resource_class: "medium"
          project-path: "Unity2D-Demo-Game-CI-CD/src"
          test-platform: "playmode"
          filters: *filters
          context: orb-testing-unity
      - test:
          name: "test-linux-license"
          step-name: "Check if the tests run and results are uploaded"
          unity-license-var-name: "UNITY_ENCODED_LICENSE_2021"
          unity-username-var-name: "UNITY_USERNAME"
          unity-password-var-name: "UNITY_PASSWORD"
          executor:
            name: "unity/ubuntu"
            target_platform: "linux-il2cpp"
            editor_version: "2021.3.1f1"
            resource_class: "medium"
          project-path: "Unity2D-Demo-Game-CI-CD/src"
          test-platform: "playmode"
          filters: *filters
          context: orb-testing-unity

       # Mono Builds   
      - build-mono:
          name: "build-linux64-mono-serial"
          step-name: "Build StandaloneLinux64"
          unity-username-var-name: "UNITY_USERNAME"
          unity-password-var-name: "UNITY_PASSWORD"
          unity-serial-var-name: "UNITY_SERIAL_2021"
          executor:
            name: "unity/ubuntu"
            target_platform: "base"
            editor_version: "2021.3.1f1"
            resource_class: "large"
          project-path: "Unity2D-Demo-Game-CI-CD/src"
          build-target: StandaloneLinux64
          compress: true
          filters: *filters
          context: orb-testing-unity
      - build-mono:
          name: "build-linux64-mono-license"
          step-name: "Build StandaloneLinux64"
          unity-license-var-name: "UNITY_ENCODED_LICENSE_2021"
          unity-username-var-name: "UNITY_USERNAME"
          unity-password-var-name: "UNITY_PASSWORD"
          executor:
            name: "unity/ubuntu"
            target_platform: "base"
            editor_version: "2021.3.1f1"
            resource_class: "large"
          project-path: "Unity2D-Demo-Game-CI-CD/src"
          build-target: StandaloneLinux64
          compress: true
          filters: *filters
          context: orb-testing-unity

      - orb-tools/pack:
          filters: *filters
      - orb-tools/publish:
          orb-name: game-ci/unity
          vcs-type: << pipeline.project.type >>
          pub-type: production
          requires:
            - orb-tools/pack
          context: orb-publishing
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+$/