description: >
  Simple drop-in job to build your Unity game.

parameters:
  step-name:
    type: string
    default: Build the project
    description: |
      Specify a custom step name for the build command, if desired.
  executor:
    type: executor
    description: |
      Pick an Executor to run the build job with.
  project-path:
    type: string
    default: "."
    description: |
      Enter the path of your Unity project.
      This should be the directory that has an "Assets" folder inside it.
  build-target:
    type: string
    description: |
      The target platform of your build.
      Accepted arguments vary with Unity's version and can be found in the docs: https://docs.unity3d.com/2022.2/Documentation/ScriptReference/BuildTarget.html
  build-name:
    type: string
    default: "UnityBuild"
    description: |
      Enter the name for this build.
  compress:
    type: boolean
    default: true
    description: |
      Whether to compress the build output to a ".tar.gz" archive.
      This is recommended if you want to download the build artifacts from the GameCI dashboard.
      If left to "false" for decompressed WebGL builds, the built project can be run directly from the GameCI dashboard.

executor: << parameters.executor >>

steps:
  - checkout
  - prepare-env:
      unity-username-var-name: << parameters.unity-username-var-name >>
      unity-password-var-name: << parameters.unity-password-var-name >>
      unity-serial-var-name: << parameters.unity-serial-var-name >>
      unity-license-var-name: << parameters.unity-license-var-name >>
      project-path: <<parameters.project-path>>
  - build:
      unity-username-var-name: << parameters.unity-username-var-name >>
      unity-password-var-name: << parameters.unity-password-var-name >>
      unity-serial-var-name: << parameters.unity-serial-var-name >>
      step-name: << parameters.step-name >>
      build-name: <<parameters.build-name>>
      build-target: <<parameters.build-target>>
      project-path: <<parameters.project-path>>
      compress: <<parameters.compress>>
